name: CI - News Headlines Sentiment Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8

      # Step 4: Code quality check (optional)
      - name: Run linting
        run: |
          flake8 src backend --ignore=E501,W503

      # Step 5: Run tests
      - name: Run tests with pytest
        run: |
          pytest -v --maxfail=3 --disable-warnings

  # Optional job for deployment or Docker build
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t latest-news-sentiment .

      - name: Run container test
        run: |
          docker run --rm latest-news-sentiment python backend/app.py --help
